mgr/nvmeof: add missing CLICommand to the module
Fixed AttributeError: type object 'NVMeoF' has no attribute 'CLICommand'

Resolves: IBMCEPH-13403

Signed-off-by: Avan Thakkar <athakkar@redhat.com>
(cherry picked from commit 75e99dce767c74d3c60ecde9c6072d368ebdc762)
(cherry picked from commit 5868188f11173a9b337e29d86c309def113c081c)