mgr/dashboard: fix osd_removal status dict serialization
Resolves: IBMCEPH-17874

After https://github.com/ceph/ceph/pull/67858, the
`orch.osds.removing_status()` has changed the way it gives the response.
its now serializes the output and dashboard fails to deserialize that
properly. Fixing that here..

Currently, when you try to delete osd from the UI, it raises the below
traceback

```
2026-08-24T10:33:33.647+0000 7f15c16fc6c0  0 [dashboard ERROR dashboard.tools] Error while calling Task(ns=osd/delete, md={'svc_id': '7'})
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/dashboard/tools.py", line 551, in _run
    val = self.task.fn(*self.task.fn_args, **self.task.fn_kwargs)  # type: ignore
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/ceph/mgr/dashboard/controllers/osd.py", line 343, in delete
    pending = [osd for osd in removal_osds if osd.osd_id == int(svc_id)]
                                              ^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'osd_id'
```

Fixes: https://tracker.ceph.com/issues/79802
Signed-off-by: Nizamudeen A <nia@redhat.com>
(cherry picked from commit cf0785951a8a6e1be6bd865a652e8fbb2df2a9c7)
(cherry picked from commit 70b3b5463a124054df2534be160eeee8dada7df3)