client: clean up warnings in client
Fix warnings/errors in ceph API tests that are present in various files
that were introduced by fscrypt feature

src/client/FSCrypt.cc:90:6: error: variable 'olen' set but not used [-Werror,-Wunused-but-set-variable]
   90 |         int olen = 0;
      |             ^
src/client/FSCrypt.cc:91:6: error: variable 'line' set but not used [-Werror,-Wunused-but-set-variable]
   91 |         int line = 0;
      |             ^
src/client/FSCrypt.cc:945:2: error: is this the way to do it? [-Werror,-W#warnings]
  945 | #warning is this the way to do it?
src/client/Client.cc:11850:2: error: read holes [-Werror,-W#warnings]
 11850 | #warning read holes
       |  ^
src/client/Client.cc:11855:2: error: implement file read here [-Werror,-W#warnings]
 11855 | #warning implement file read here
       |  ^
src/client/Inode.cc:847:2: error: need to make sure that we do not skip entire subtree somehow [-Werror,-W#warnings]
  847 | #warning need to make sure that we do not skip entire subtree somehow
      |  ^

Resolves: ISCE-3051

Signed-off-by: Christopher Hoffman <choffman@redhat.com>
(cherry picked from commit ee9096686e41a7a6c57f39782ef3ade681babb0c)