mgr/cephadm: add logic to handle certmgr errors and warnings
Add support in certmgr to distinguish between warnings and
errors. Previously, a single code (CEPHADM_CERT_ERROR) was used for
both, which complicated the Dashboard logic and forced ad-hoc checks
to determine whether a reported event was a warning or an error. In the
new code, CEPHADM_CERT_ERROR and CEPHADM_CERT_WARNING are used to
clearly distinguish between the two cases such as:

CEPHADM_CERT_ERROR: only INVALID/EXPIRED certificates
CEPHADM_CERT_WARNING: only EXPIRING certificates

https://tracker.ceph.com/issues/74467
Resolves: ISCE-2442

Signed-off-by: Redouane Kachach <rkachach@ibm.com>
(cherry picked from commit 868ed589f294ccf6ccc5c4c61ac080f90d9bae84)