mgr/cephadm: fix OSD getstate nulling wrong attr and mutating obj
OSD.__getstate__ has two bugs:

1. Wrong key name: the attribute is stored as self.rm_util but __getstate__
   was nulling 'remove_util' (the constructor parameter name) instead. Since
   these are different keys, rm_util was never nulled and still held a reference
   to RemoveUtil -> CephadmOrchestrator when pickle tried to serialize the OSD
   object. This caused:

     TypeError: cannot pickle 'CephadmOrchestrator' object

   which surfaced as:

     RuntimeError: Remote method threw exception: TypeError: cannot pickle
     'CephadmOrchestrator' object

   when calling `ceph orch osd rm status`, breaking the OSD removal wait loop
   in tests and in production.

2. In-place mutation: self.__dict__.update(...) modified the live object
   rather than returning a copy. Any code running on that OSD instance after
   pickling (e.g. the removal loop in another thread) would find rm_util=None
   and crash.

Fix: return a copy of __dict__ with the correct key (rm_util) set to None.

Fixes: https://tracker.ceph.com/issues/74862
Signed-off-by: Redouane Kachach <rkachach@ibm.com>